core/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("main.urls"))
]

main/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import *

app_name = "main"
urlpatterns = [
    path('details/',detail,name="detail"),
    path("index",index,name="index")

]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render

# Create your views here.
def detail(request):
    return render(request,"main/detail.html")
def index(request):
    return render(request,"main/index.html")

main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'main/bootstrap.min.css' %}">
</head>
<body>
    <header>
        {% include 'main/header.html' %}
        {% block header %}
        {% endblock %}
    </header>
    <main>
        {% block content %}
        {% endblock %}
    </main>
    <footer>
        {% include 'main/footer.html' %}

        {% block footer %}
        {% endblock %}
    </footer>
</body>
</html>

main/templates/main/detail.html
{% extends 'main/base.html' %}

{% block title %}
Details | App
{% endblock %}
{% block content %}

<a href="{% url 'main:index' %}">index html link</a>
{% endblock %}

main/templates/main/footer.html
{% block footer %}
<div class="container">
    <footer class="py-3 my-4">
      <ul class="nav justify-content-center border-bottom pb-3 mb-3">
        <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Home</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Features</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Pricing</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">FAQs</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">About</a></li>
      </ul>
      <p class="text-center text-muted">© 2023 Ali Hassan</p>
    </footer>
  </div>
{% endblock %}

main/templates/main/header.html
{% block header %}
<nav class="navbar navbar-expand-lg bg-light rounded" aria-label="Thirteenth navbar example">
    <div class="container-fluid">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample11" aria-controls="navbarsExample11" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse d-lg-flex" id="navbarsExample11">
        <a class="navbar-brand col-lg-3 me-0" href="#">Ali hassan</a>
        <ul class="navbar-nav col-lg-6 justify-content-lg-center">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled">Disabled</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown" aria-expanded="false">Dropdown</a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="#">Action</a></li>
              <li><a class="dropdown-item" href="#">Another action</a></li>
              <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
          </li>
        </ul>
        <div class="d-lg-flex col-lg-3 justify-content-lg-end">
          <button class="btn btn-primary">Button</button>
        </div>
      </div>
    </div>
  </nav>
{% endblock %}

main/templates/main/index.html
{% extends 'main/base.html' %}
{% block title %}
Index | App
{% endblock %}
{% block content %}
<a href="{% url 'main:detail' %}">detail html link</a>
{% endblock %}